Repository justenanderson-commits/whats-cookin, pull requests merged in 2022-11, with the labels that each got.

#82 Adds deep equal to certain tests and adds tests for the User properties
  test/Recipe-test.js
  test/User-test.js
Labels: Testing, Refactor

#80 Fix/ryan ingredient singular
  src/classes/Ingredient.js
  test/Ingredient-test.js
Labels: Refactor

#81 Refactor/thomas recipe method
  src/classes/Recipe.js
  src/data/ingredients.js
  src/data/recipes.js
  src/data/users.js
  src/scripts.js
Labels: DOM Display, bug fix, API

#83 Fix/justen search error messages
  dist/index.html
  src/scripts.js
Labels: bug fix

#85 Add sad path tests to RecipeRepo and User
  test/RecipeRepository-test.js
  test/User-test.js
Labels: Testing

#89 Refactor/thomas recipe test
  src/classes/Recipe.js
  src/ingredient-test-data.js
  test/Recipe-test.js
Labels: documentation, Testing, bug fix

#91 Feat/pantry class
  src/classes/Pantry.js
  src/classes/User.js
  src/scripts.js
  src/test-data/Pantry-test-data.js
  src/test-data/Recipe-data.js
  test/Pantry-test.js
Labels: Feature

#97 Refactors some of the recipe methods
  src/classes/Recipe.js
  src/scripts.js
  test/Recipe-test.js
Labels: Testing, Refactor

#92 Fix/branch error
  src/classes/Pantry.js
  src/test-data/ingredient-test-data.js
  test/Pantry-test.js
  test/Recipe-test.js
Labels: enhancement

#95 Feat/ryan pantry view
  dist/index.html
  src/classes/Pantry.js
  src/scripts.js
  src/styles.css
  src/test-data/Pantry-test-data.js
  src/test-data/Recipe-data.js
  test/Pantry-test.js
  test/Recipe-test.js
Labels: enhancement, Testing, Feature, DOM Display

#96 Feat/thomas all recipes list
  README.md
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement, html, CSS, DOM Display, bug fix, Refactor, UI/UX, Accessibility

#99 Feat/angie search not case sensitive
  src/classes/RecipeRepository.js
Labels: enhancement, bug fix

#101 Testing/thomas pantry
  src/classes/Pantry.js
  src/classes/Recipe.js
  test/Pantry-test.js
  test/Recipe-test.js
Labels: Testing, Refactor

#100 Feat/ryan add to pantry
  dist/index.html
  src/classes/Pantry.js
  src/classes/User.js
  src/scripts.js
  src/styles.css
Labels: Feature, DOM Display

#103 Feat/ryan add ingredient follow up
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#104 Corrects fetchData with the right url
  src/apiCalls.js
  src/scripts.js
Labels: bug fix, API

#106 Feat/cook recipe functionality
  dist/index.html
  src/apiCalls.js
  src/classes/Pantry.js
  src/scripts.js
  src/styles.css
Labels: Feature

#117 Feat/angie display missing
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: DOM Display

#114 styles my pantry submit button
  dist/index.html
Labels: DOM Display, UI/UX

#115 Fix/ryan hide my recipes section
  dist/index.html
  src/classes/User.js
  src/scripts.js
  test/User-test.js
Labels: DOM Display

#112 Test for adding ingredients to pantry
  src/classes/User.js
  test/User-test.js
Labels: Testing

#116 Fix/justen move test data
  src/classes/Recipe.js
  src/test-data/Recipe-data.js
  src/test-data/Recipe-repo-test-data.js
  src/test-data/User-test-data.js
  test/Recipe-test.js
  test/RecipeRepository-test.js
  test/User-test.js
Labels: Testing, Refactor

#118 Fix User test issue
  test/User-test.js
Labels: Testing, Refactor

#119 Clears the shopping list
  src/scripts.js
Labels: bug fix

#120 Fixed the add ingredient button
  dist/index.html
Labels: bug fix
