Repository justenanderson-commits/whats-cookin, pull requests merged in 2022-10, with the labels that each got.

#1 Add method to the RecipeRepository class.
  src/classes/RecipeRepository.js
  src/data/ingredients.js
  src/data/recipes.js
  src/data/users.js
  test/RecipeRepository-test.js
Labels: enhancement

#2 Adds the reamingin methods and tests for recipieRepo
  src/classes/RecipeRepository.js
  test/RecipeRepository-test.js
Labels: enhancement

#4 Add initial HTML
  dist/index.html
  package.json
  src/styles.css
Labels: enhancement

#3 Add the ingredients class
  src/classes/IngredientsClass.js
  test/IngredientsClass-test.js
Labels: enhancement

#7 Add basic CSS styling.
  dist/index.html
  src/styles.css
Labels: enhancement

#8 Feat/thomas iteration 1 recipe
  src/classes/IngredientsClass.js
  src/classes/Recipe.js
  test/RecipeRepository-test.js
  test/Recipie-test.js
Labels: Testing, Feature

#10 Fix image paths for webpack
  dist/index.html
Labels: html

#12 Add the User class and methods to add and remove recipes
  package.json
  src/classes/UserClass.js
  test/UserClass-test.js
Labels: enhancement

#22 Feat/ryan html v2
  dist/index.html
  src/styles.css
Labels: Feature, html, CSS

#25 Feat/angie user v2
  src/classes/Ingredient.js
  src/classes/Recipe.js
  src/classes/User.js
  src/classes/UserClass.js
  test/Ingredient-test.js
  test/Recipe-test.js
  test/User-test.js
  test/UserClass-test.js
Labels: Feature

#26 Feat/justen html css v2
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#27 Add recipe names in when clicking All Recipes
  dist/index.html
  src/data/recipes.js
  src/scripts.js
  src/styles.css
Labels: bug, enhancement

#28 Feat/ryan recipe details displayed
  dist/index.html
  src/classes/Recipe.js
  src/classes/RecipeRepository.js
  src/scripts.js
  src/styles.css
Labels: enhancement, Feature

#30 Fix/justen user test
  src/classes/Recipe.js
  test/Recipe-test.js
Labels: bug

#31 Adds to displayRecipeDetails
  src/scripts.js
Labels: DOM Display

#32 Add functionality to clicking carousel
  dist/index.html
  src/scripts.js
Labels: enhancement, DOM Display

#33 Rename the function returnRecipeIngredientsInfo() and fix the bug of …
  src/scripts.js
Labels: bug

#34 Feat/angie user v2
  src/classes/User.js
  test/User-test.js
Labels: enhancement

#35 Add functionality of filter
  dist/index.html
  src/scripts.js
Labels: enhancement, DOM Display

#37 Add ability to search all recipes by name
  dist/index.html
  src/classes/RecipeRepository.js
  src/scripts.js
  src/styles.css
Labels: enhancement, DOM Display

#36 Feat/justen saved recipes section v1
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#38 Feat/angie save button
  dist/index.html
  src/scripts.js
Labels: DOM Display

#40 Feat/justen hover pointer
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: CSS

#39 Feat/ryan filter
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement, DOM Display

#41 Add a header to the saved recipe page
  dist/index.html
Labels: DOM Display

#42 Feat/thomas user dom
  dist/index.html
  src/images/cooking.png
  src/scripts.js
Labels: Feature, DOM Display, bug fix

#44 Revert "Feat/thomas user dom"
  dist/index.html
  src/images/cooking.png
  src/scripts.js
Labels: bug

#43 Fix styling on Prev and Next buttons and add rounded edges to images …
  src/styles.css
Labels: CSS

#45 Add styling changes to headers, font size, and body height
  dist/index.html
  src/styles.css
Labels: html, CSS

#46 Update scripts.js
  src/scripts.js
Labels: documentation, DOM Display, bug fix

#48 Feat/justen recipe details pic
  dist/index.html
  src/classes/Recipe.js
  src/scripts.js
  src/styles.css
Labels: enhancement

#50 Add functionality to remove recipes from My Recipes
  dist/index.html
  src/classes/User.js
  src/scripts.js
  src/styles.css
Labels: enhancement, DOM Display

#49 Adds a comma to the welcome
  src/scripts.js
Labels: bug fix

#52 Update all font to comic sans. Old font code left in place for future…
  src/styles.css
Labels: Feature

#53 Adds fetches
  src/apiCalls.js
  src/scripts.js
Labels: enhancement, DOM Display
